# Generated by Django 2.1.5 on 2019-02-07 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('birth_month', models.CharField(max_length=80)),
                ('birth_day', models.IntegerField()),
                ('birth_year', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=80)),
                ('country', models.CharField(max_length=80)),
                ('zip_code', models.IntegerField()),
                ('degree', models.CharField(max_length=80)),
                ('school', models.CharField(max_length=100)),
                ('school_address', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('month_status', models.CharField(max_length=80)),
                ('year_status', models.IntegerField()),
                ('job_title', models.CharField(max_length=80)),
                ('company_name', models.CharField(max_length=100)),
                ('company_address', models.CharField(max_length=100)),
                ('company_month_f', models.CharField(max_length=80)),
                ('company_year_f', models.IntegerField()),
                ('company_month_t', models.CharField(max_length=80)),
                ('company_year_t', models.IntegerField()),
                ('hobbies', models.CharField(max_length=250)),
                ('skills', models.CharField(max_length=250)),
                ('languages', models.CharField(max_length=250)),
                ('refrerences', models.CharField(max_length=250)),
                ('summary', models.CharField(max_length=250)),
            ],
        ),
    ]
