# Generated by Django 2.1.5 on 2019-02-19 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResumeTemp',
        ),
    ]
